# Generated by Django 4.0.3 on 2022-03-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glrweb', '0002_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
